[book]
authors = [ "Zonemaster Team" ]
description = "Zonemaster documentation"
language = "en"
src = "./"

[output.html]
no-section-label = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
level = 1

[preprocessor.index]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.linkcheck]
follow-web-links = false
